import { Branding } from "./BrandMark";
import { Icon } from "./Icons";

export function FirstRunCard({
  onOpenFromDisk,
  onTryDemo,
}: {
  onOpenFromDisk: () => void;
  onTryDemo: () => void;
}) {
  return (
    <div className="firstrun-wrap">
      <div className="firstrun">
        <Branding />
        <p className="welcome-label">Welcome</p>
        <h1>Open a world to begin</h1>
        <p className="lede">
          Cradle is a read-only inspector for worlds generated by <b>canon</b>. Point it at a folder on disk that contains a <code>data/manifest.json</code> and walk its rooms, NPCs, items and dialogue.
        </p>

        <div className="fr-steps">
          <div className="fr-step">
            <span className="num">01</span>
            <span><b>Open a world from disk</b> <span className="dim">— pick a folder with a canon-generated World Bible.</span></span>
          </div>
          <div className="fr-step">
            <span className="num">02</span>
            <span><b>Or try the bundled demo</b> <span className="dim">— <code>bibles/mazeworld_5_room_demo</code>, 5 rooms, fully validated.</span></span>
          </div>
          <div className="fr-step">
            <span className="num">03</span>
            <span><b>Don't have a world yet?</b> <span className="dim">— generate one with canon's MazeWorld reference implementation.</span></span>
          </div>
        </div>

        <div className="cta-row">
          <button className="cta-primary" onClick={onOpenFromDisk}>
            <Icon id="g-folder" size={14} className="g g-on-cta" />
            Open world from disk
            <span className="kbd">⌘O</span>
          </button>
          <button className="cta-secondary" onClick={onTryDemo}>
            <Icon id="g-doc" size={14} />
            Try the bundled demo
          </button>
        </div>

        <div className="fr-foot">
          <span>no world loaded</span>
          <a href="https://github.com/Demi-Build/canon-ai" target="_blank" rel="noreferrer">
            What is canon? →
          </a>
        </div>
      </div>
    </div>
  );
}
